# Form implementation generated from reading ui file 'RSA.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import tkinter as tk
from tkinter import filedialog
import random

# Hàm băm 
def hambam(text):
    # Khởi tạo các hằng số
    h0 = 0x6a09e667
    h1 = 0xbb67ae85
    h2 = 0x3c6ef372
    h3 = 0xa54ff53a
    h4 = 0x510e527f
    h5 = 0x9b05688c
    h6 = 0x1f83d9ab
    h7 = 0x5be0cd19

    # Khởi tạo danh sách các hằng số
    k = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
        0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
        0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
        0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
        0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
        0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
        0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2
    ]

    # Chuyển đổi chuỗi thành dạng byte
    byte_string = bytearray(text.encode('utf-8'))

    # Thêm byte padding
    byte_string.append(0x80)

    while len(byte_string) % 64 != 56:
        byte_string.append(0x00)

    # Gắn vào 64 bit cuối của độ dài chuỗi
    length = len(text) * 8
    byte_string += length.to_bytes(8, 'big')

    # Tạo các block 512-bit từ chuỗi byte
    blocks = [byte_string[i:i + 64] for i in range(0, len(byte_string), 64)]

    for block in blocks:
        # Tạo danh sách từng từ 32-bit từ block
        words = [int.from_bytes(block[i:i + 4], 'big') for i in range(0, 64, 4)]

        # Mở rộng từ 16-word đến 64-word
        for i in range(16, 64):
            s0 = right_rotate(words[i - 15], 7) ^ right_rotate(words[i - 15], 18) ^ (words[i - 15] >> 3)
            s1 = right_rotate(words[i - 2], 17) ^ right_rotate(words[i - 2], 19) ^ (words[i - 2] >> 10)
            words.append((words[i - 16] + s0 + words[i - 7] + s1) & 0xffffffff)

        # Khởi tạo các biến băm
        a = h0
        b = h1
        c = h2
        d = h3
        e = h4
        f = h5
        g = h6
        h = h7

        # Thực hiện vòng lặp chính
        for i in range(64):
            S1 = right_rotate(e, 6) ^ right_rotate(e, 11) ^ right_rotate(e, 25)
            ch = (e & f) ^ ((~e) & g)
            temp1 = (h + S1 + ch + k[i] + words[i]) & 0xffffffff
            S0 = right_rotate(a, 2) ^ right_rotate(a, 13) ^ right_rotate(a, 22)
            maj = (a & b) ^ (a & c) ^ (b & c)
            temp2 = (S0 + maj) & 0xffffffff

            h = g
            g = f
            f = e
            e = (d + temp1) & 0xffffffff
            d = c
            c = b
            b = a
            a = (temp1 + temp2) & 0xffffffff

        # Cộng thêm các giá trị ban đầu
        h0 = (h0 + a) & 0xffffffff
        h1 = (h1 + b) & 0xffffffff
        h2 = (h2 + c) & 0xffffffff
        h3 = (h3 + d) & 0xffffffff
        h4 = (h4 + e) & 0xffffffff
        h5 = (h5 + f) & 0xffffffff
        h6 = (h6 + g) & 0xffffffff
        h7 = (h7 + h) & 0xffffffff

    # Kết hợp các giá trị băm thành chuỗi kết quả
    hashed_text = '{:08x}{:08x}{:08x}{:08x}{:08x}{:08x}{:08x}{:08x}'.format(h0, h1, h2, h3, h4, h5, h6, h7)

    return hashed_text

def right_rotate(value, count):
    return ((value >> count) | (value << (32 - count))) & 0xffffffff

# Kiểm tra số nguyên tố 
def is_prime(p):
    if p < 2:
        return False
    for i in range(2, int(p**0.5) + 1):
        if p % i == 0:
            return False
    return True
# Thuật toán Oclip mở rộng 
def extended_euclidean_algorithm(a, b):
    if b == 0:
        return a, 1, 0

    gcd, x1, y1 = extended_euclidean_algorithm(b, a % b)
    x = y1
    y = x1 - (a // b) * y1

    return gcd, x, y

def mod_inverse(a, m):
    gcd, x, y = extended_euclidean_algorithm(a, m)
    return x % m
# Tìm ước chung nhỏ nhất của hai số 
def find_gcd(a, b): # Hàm tìm UCLN
    while b != 0:
        a, b = b, a % b
    return a
# Chia A^B mod C
def mod(alpha,a,p):
    res = 1
    alpha = alpha % p
    while a>0:
        if a%2==1:
            res = (res * alpha) % p
        a = a // 2
        alpha = (alpha * alpha) % p
    return res

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 780)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 721))
        self.frame.setStyleSheet("background-color: white")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.line = QtWidgets.QFrame(parent=self.frame)
        self.line.setGeometry(QtCore.QRect(390, 10, 16, 691))
        self.line.setStyleSheet("color: black")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 71, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 71, 41))
        self.label_3.setObjectName("label_3")
        self.soP = QtWidgets.QLineEdit(parent=self.frame)
        self.soP.setGeometry(QtCore.QRect(130, 70, 201, 31))
        self.soP.setStyleSheet("")
        self.soP.setObjectName("soP")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 170, 71, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(40, 220, 71, 41))
        self.label_5.setObjectName("label_5")
        self.soDa = QtWidgets.QLabel(parent=self.frame)
        self.soDa.setGeometry(QtCore.QRect(130, 220, 300, 31))
        self.soDa.setObjectName("soDa")

        self.sinhkhoa = QtWidgets.QPushButton(parent=self.frame)
        self.sinhkhoa.setGeometry(QtCore.QRect(50, 310, 131, 28))
        self.sinhkhoa.setObjectName("sinhkhoa")
        self.sinhkhoa.setStyleSheet("background-color: lightsalmon")

        self.xacnhan = QtWidgets.QPushButton(parent=self.frame)
        self.xacnhan.setGeometry(QtCore.QRect(250, 310, 100, 28))
        self.xacnhan.setObjectName("xacnhan")
        self.xacnhan.setStyleSheet("background-color: lightsalmon")

        self.ct2 = QtWidgets.QPushButton(parent=self.frame)
        self.ct2.setGeometry(QtCore.QRect(680, 180, 93, 28))
        self.ct2.setObjectName("Nhận khóa")
        self.ct2.setStyleSheet("background-color: lightsalmon")

        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 260, 171, 31))
        self.label_6.setObjectName("label_6")
        self.Ne = QtWidgets.QLabel(parent=self.frame)
        self.Ne.setGeometry(QtCore.QRect(180, 260, 200, 31))
        self.Ne.setObjectName("Ne")
        self.chukya = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.chukya.setGeometry(QtCore.QRect(30, 410, 331, 81))
        self.chukya.setObjectName("chukya")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setGeometry(QtCore.QRect(40, 360, 71, 31))
        self.label_7.setObjectName("label_7")
        self.mahoaa = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.mahoaa.setGeometry(QtCore.QRect(30, 560, 331, 81))
        self.mahoaa.setObjectName("mahoaa")
        self.label_8 = QtWidgets.QLabel(parent=self.frame)
        self.label_8.setGeometry(QtCore.QRect(40, 510, 121, 31))
        self.label_8.setObjectName("label_8")
        self.mahoa = QtWidgets.QPushButton(parent=self.frame)
        self.mahoa.setGeometry(QtCore.QRect(270, 510, 93, 28))
        self.mahoa.setObjectName("mahoa")
        self.mahoa.setStyleSheet("background-color: lightsalmon")
        self.ct = QtWidgets.QPushButton(parent=self.frame)
        self.ct.setGeometry(QtCore.QRect(270, 660, 93, 28))
        self.ct.setObjectName("ct")
        self.ct.setStyleSheet("background-color: lightsalmon")
        self.label_9 = QtWidgets.QLabel(parent=self.frame)
        self.label_9.setGeometry(QtCore.QRect(420, 10, 171, 31))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.frame)
        self.label_10.setGeometry(QtCore.QRect(430, 60, 71, 41))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.frame)
        self.label_11.setGeometry(QtCore.QRect(430, 120, 71, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        self.label_12.setGeometry(QtCore.QRect(430, 180, 91, 31))
        self.label_12.setObjectName("label_12")
        self.chukyb = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.chukyb.setGeometry(QtCore.QRect(440, 240, 311, 91))
        self.chukyb.setObjectName("chukyb")
        self.mahoab = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.mahoab.setGeometry(QtCore.QRect(440, 470, 311, 91))
        self.mahoab.setObjectName("mahoab")
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setGeometry(QtCore.QRect(430, 400, 211, 31))
        self.label_13.setObjectName("label_13")
        self.ktra = QtWidgets.QPushButton(parent=self.frame)
        self.ktra.setGeometry(QtCore.QRect(540, 580, 121, 28))
        self.ktra.setObjectName("ktra")
        self.ktra.setStyleSheet("background-color: lightsalmon")
        self.save = QtWidgets.QPushButton(parent=self.frame)
        self.save.setGeometry(QtCore.QRect(40, 660, 93, 28))
        self.save.setObjectName("save")
        self.save.setStyleSheet("background-color: lightsalmon")
        self.open = QtWidgets.QPushButton(parent=self.frame)
        self.open.setGeometry(QtCore.QRect(680, 400, 93, 28))
        self.open.setObjectName("open")
        self.open.setStyleSheet("background-color: lightsalmon")
        self.soQ = QtWidgets.QLineEdit(parent=self.frame)
        self.soQ.setGeometry(QtCore.QRect(130, 120, 201, 31))
        self.soQ.setStyleSheet("")
        self.soQ.setObjectName("soQ")
        self.soE = QtWidgets.QLineEdit(parent=self.frame)
        self.soE.setGeometry(QtCore.QRect(130, 170, 201, 31))
        self.soE.setStyleSheet("")
        self.soE.setObjectName("soE")
        self.soN = QtWidgets.QLineEdit(parent=self.frame)
        self.soN.setGeometry(QtCore.QRect(500, 60, 201, 31))
        self.soN.setStyleSheet("")
        self.soN.setObjectName("soN")
        self.soE2 = QtWidgets.QLineEdit(parent=self.frame)
        self.soE2.setGeometry(QtCore.QRect(500, 120, 201, 31))
        self.soE2.setStyleSheet("")
        self.soE2.setObjectName("soE2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.sinhkhoa.clicked.connect(self.Sinhkhoa)
        self.xacnhan.clicked.connect(self.Xacnhan)
        self.ct2.clicked.connect(self.Nhankhoa)
        self.mahoa.clicked.connect(self.Mahoa)
        self.ct.clicked.connect(self.Chuyentiep)
        self.ktra.clicked.connect(self.Ktra)
        self.open.clicked.connect(self.Open)
        self.save.clicked.connect(self.Save)
    # Lưu File
    def Save(self):
        plain = self.mahoaa.toPlainText()
        filetypes = (
            ('Text files', '*.TXT'),
            ('All files', '*.*'),
        )
        root = tk.Tk()
        filename = tk.filedialog.asksaveasfilename(
            title='Save as...',
            filetypes=filetypes,
            defaultextension='.txt'
        )
     
        root.destroy()
        file = open(filename,"w")
        file.write(plain)
        file.close()
    # Mở File 
    def Open(self):
        filetypes = (
            ('Text files', '*.TXT'),
            ('All files', '*.*'),
        )
        root = tk.Tk()
        filename = tk.filedialog.askopenfilename(
            title='Select a file...',
            filetypes=filetypes,
        )
        root.destroy()
        file = open(filename, "r")
        pla = file.read()
        self.mahoab.setPlainText(str(pla))
        file.close()
    # Xác nhận chữ ký có chính xác hay không 
    def Ktra(self):
        d = int(self.soE2.text())
        n = int(self.soN.text())
        plain = self.chukyb.toPlainText()
        bam = hambam(plain)
        v = ""
        mahoa = self.mahoab.toPlainText()
        mahoa = mahoa.strip()
        spl = mahoa.split(" ")
        for i in spl:
            m = int(i)
            kt = mod(m,d,n)
            kt = kt % 255
            v = v + chr(kt)
        if v == bam:
            msg = QtWidgets.QMessageBox()
            msg.setInformativeText('Chữ ký đúng!')
            msg.setStyleSheet("background-color: pink; text-align: center")
            msg.exec()
    # Chuyển nội dung 
    def Chuyentiep(self):
        plain = self.mahoaa.toPlainText()
        self.mahoab.setPlainText(str(plain))
    # Mã Hóa 
    def Mahoa(self):
        plain = self.chukya.toPlainText()
        hashcode = hambam(plain)
        
        e = int(self.soE.text())
        p = int(self.soP.text())
        q = int(self.soQ.text())
        n = p*q;
        list = ""
        for i in hashcode:
            f = ord(i) # Chuyển string sang int bảng ASCII
            v = mod(f,e,n)
            list = list+str(v)+" "
        self.mahoaa.setPlainText(str(list))
    # Nhận khóa công khai từ bên gửi 
    def Nhankhoa(self):
        p = int(self.soP.text())
        q = int(self.soQ.text())
        e = int(self.soE.text())
        d = int(self.soDa.text())
        n = p*q;
        self.soN.setText(str(n))
        self.soE2.setText(str(d))
    # Tính số Da
    def Xacnhan(self):
        p = int(self.soP.text())
        q = int(self.soQ.text())
        e = int(self.soE.text())
        n = p*q;
        phi = (p-1)*(q-1)
        # Tính số nghịch đảo 
        d = mod_inverse(e,phi) 
        
        self.soDa.setText(str(d))
        self.Ne.setText("(d,n): "+"("+str(d)+" , "+str(n)+")")
    # Sinh khoa ngẫu nhiên 
    def Sinhkhoa(self):
       
        pv = int(random.randint(1000, 1000000))
        while not is_prime(pv):
            pv = int(random.randint(1000, 1000000))
        self.soP.setText(str(pv))
    
        qv = int(random.randint(1000, 1000000))
        while not is_prime(qv):
            qv = int(random.randint(1000, 1000000))
        self.soQ.setText(str(qv))
        phi = (pv-1)*(qv-1)
    
        ev = int(random.randint(100000, 100000000))
        while (not is_prime(ev)) and ev < phi:
            ev = int(random.randint(1000, 1000000))
        self.soE.setText(str(ev))
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Tạo khóa</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Số P</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Số Q</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Số E</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Số d</span><span style=\" font-size:10pt; vertical-align:sub;\">A</span></p></body></html>"))
        self.soDa.setText(_translate("MainWindow", ""))
        self.sinhkhoa.setText(_translate("MainWindow", "Sinh khóa tự động"))
        self.xacnhan.setText(_translate("MainWindow", "Xác nhận"))
        self.ct2.setText(_translate("MainWindow", "Nhận khóa"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Khóa Kiểm thử</span></p></body></html>"))
        self.Ne.setText(_translate("MainWindow", ""))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Chữ ký</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Văn bản mã hóa</span></p></body></html>"))
        self.mahoa.setText(_translate("MainWindow", "Mã hóa"))
        self.ct.setText(_translate("MainWindow", "Chuyển tiếp"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Khóa kiểm thử</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Số N</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Số d</span><span style=\" font-size:10pt; vertical-align:sub;\">A</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Chữ ký</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Văn bản mã hóa nhận được</span></p></body></html>"))
        self.ktra.setText(_translate("MainWindow", "Kiểm tra chữ ký"))
        self.save.setText(_translate("MainWindow", "Lưu file"))
        self.open.setText(_translate("MainWindow", "Mở file"))
        self.soP.setStyleSheet("border: 1px solid #333; border-radius: 5px")
        self.soQ.setStyleSheet("border: 1px solid #333;border-radius: 5px")
        self.soE.setStyleSheet("border: 1px solid #333;border-radius: 5px")
        self.soN.setStyleSheet("border: 1px solid #333;border-radius: 5px")
        self.soE2.setStyleSheet("border: 1px solid #333;border-radius: 5px")
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
